server:
  port: 8123
  servlet:
    context-path: /api/interface

spring:
  application:
    name: api-interface

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxx
    username: xxx
    password: xxx

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
yuapi:
  client:
    secret-key: xxx
    access-key: xxx

